---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-mysql-1
  labels:
    app: mysql
spec:
  accessModes:
    - ReadWriteOnce
  resources: 
    requests:
      storage: 20Gi
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - image: "mysql:5.6"
        name: mysql
        imagePullPolicy: Always
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: wordpress-mysql-1
      restartPolicy: Always
      volumes:
      - name: wordpress-mysql-1
        persistentVolumeClaim:
          claimName: wordpress-mysql-1
