---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: wordpress-data-1
  labels:
    type: local
    app: wordpress
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /tmp/data/wordpress-data-1
  persistentVolumeReclaimPolicy: Recycle
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: wordpress-mysql-1
  labels:
    type: local
    app: wordpress
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /tmp/data/mysql-data-1
  persistentVolumeReclaimPolicy: Recycle
