# requires galaxy roles:
# - willshersystems.sshd (https://galaxy.ansible.com/willshersystems/sshd)

# run before:
# ansible-galaxy init
# ansible-galaxy install willshersystems.sshd
---
- hosts: all
  vars:
    sshd_skip_defaults: true
    sshd:
      Compression: true
      ListenAddress:
        - "0.0.0.0"
        - "::"
      GSSAPIAuthentication: no
      Match:
        - Condition: "Group user"
          GSSAPIAuthentication: yes
    sshd_UsePrivilegeSeparation: no
    sshd_match:
        - Condition: "Group xusers"
          X11Forwarding: yes
  roles:
    - role: willshersystems.sshd
