apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: backend-dep-scaler
  labels:
    sample: horizontalpodautoscaler
spec:
  maxReplicas: 10
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: banb-deployment
  targetCPUUtilizationPercentage: 50
