apiVersion: apps/v1
kind: Deployment
metadata:
  name: quizapp-deployment
  labels:
    app: quizapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quizapp
  template:
    metadata:
      labels:
        app: quizapp
    spec:
      containers:
      - name: quizapp
        image: quay.io/nibalizer/quizapp
        #        command: ["/bin/sleep", "infinity"]
        imagePullPolicy: Always
        env:
        - name: DEBUG
          value: "FALSE"
---
apiVersion: v1
kind: Service
metadata:
  name: quizapp
  labels:
    app: quizapp
spec:
  ports:
  - port: 3000
    protocol: TCP
  selector:
    app: quizapp
---
 apiVersion: networking.k8s.io/v1beta1
 kind: Ingress
 metadata:
   name: myingress
 spec:
   rules:
   - host: nibz-tf-schematics-5290c8c8e5797924dc1ad5d1b85b37c0-0000.us-south.containers.appdomain.cloud
     http:
       paths:
       - path: /
         backend:
           serviceName: quizapp
           servicePort: 3000
